# Generated by Django 3.0.5 on 2020-04-11 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('-manu_num',), 'verbose_name': '제조업체', 'verbose_name_plural': '제조업체들'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('-date_joined',), 'verbose_name': '유저', 'verbose_name_plural': '유저들'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_ordered',), 'verbose_name': '주문', 'verbose_name_plural': '주문들'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-supply_date',), 'verbose_name': '제품', 'verbose_name_plural': '제품들'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='location',
            field=models.CharField(max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manu_name',
            field=models.CharField(max_length=50, verbose_name='제조업체명'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manu_num',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='제조업체번호 PK'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='supervisor',
            field=models.CharField(max_length=30, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성'), ('neither', '선택 안함')], default='male', max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='location',
            field=models.CharField(max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=20, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pro_num',
            field=models.ManyToManyField(through='api.Order', to='api.Product', verbose_name='구매한 상품'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='주문일자'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=100, verbose_name='배송지'),
        ),
        migrations.AlterField(
            model_name='order',
            name='many',
            field=models.IntegerField(verbose_name='주문수량'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=300, verbose_name='주문요청메시지'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pro_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product', verbose_name='상품번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MyUser', verbose_name='유저 id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(verbose_name='재고량'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manu_num',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='api.Manufacturer', verbose_name='제조업체번호'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='단가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_num',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='상품번호 PK'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_date',
            field=models.DateTimeField(verbose_name='공급일자'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_vol',
            field=models.IntegerField(verbose_name='공급량'),
        ),
    ]
