# Generated by Django 3.0.5 on 2020-04-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('AC', 'action'), ('DR', 'drama'), ('CM', 'comedy'), ('SP', 'sport'), ('WS', 'western'), ('EP', 'epic'), ('AD', 'adventure'), ('RM', 'romance'), ('SF', 'science_fiction'), ('MS', 'mystery'), ('FT', 'fantasy'), ('WR', 'war'), ('TH', 'thriller'), ('DC', 'documentary'), ('DS', 'disaster'), ('MU', 'musical'), ('HR', 'horror')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(choices=[('G', 'gold'), ('S', 'silver'), ('V', 'vip')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workers',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position',
            field=models.CharField(blank=True, choices=[('TK', 'ticket'), ('CL', 'cleaning'), ('CO', 'counter'), ('FD', 'food')], max_length=10, null=True),
        ),
    ]
