# Generated by Django 3.0.5 on 2020-04-12 00:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200412_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-supply_date',), 'verbose_name': '상품', 'verbose_name_plural': '상품들'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pro_name',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_num', models.AutoField(primary_key=True, serialize=False, verbose_name='배송번호 PK')),
                ('date_delivered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='배송일자')),
                ('transport', models.IntegerField(verbose_name='운송장번호')),
                ('state', models.CharField(choices=[('preparing', '상품준비중'), ('departure', '배송출발'), ('in_progress', '배송중'), ('completed', '배송완료')], default='preparing', max_length=20, verbose_name='배송상태')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
            ],
        ),
    ]
