# Generated by Django 3.0.5 on 2020-04-23 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200419_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='pro_num',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manu_num',
        ),
        migrations.AddField(
            model_name='myuser',
            name='product',
            field=models.ManyToManyField(related_name='purchased_users', through='api.Order', to='api.Product', verbose_name='구매한 상품'),
        ),
        migrations.AddField(
            model_name='order',
            name='myuser',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.MyUser', verbose_name='유저'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.Product', verbose_name='상품'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=django.utils.timezone.now, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.Manufacturer', verbose_name='제조업체'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('myuser', 'product')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='pro_num',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
    ]
