# Generated by Django 3.0.3 on 2020-04-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_no', models.IntegerField(primary_key=True, serialize=False)),
                ('is_reservation', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Branch')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Theater')),
            ],
        ),
    ]
