# Generated by Django 3.0.3 on 2020-04-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_screen'),
    ]

    operations = [
        migrations.RemoveField('Screen', 'total_seat', field=None),
    ]
