# Generated by Django 3.0.5 on 2020-04-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
