# Generated by Django 3.0.5 on 2020-04-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200412_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supply_date',
            field=models.DateField(verbose_name='공급일자'),
        ),
    ]
