# Generated by Django 3.0.5 on 2020-04-14 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200414_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.SmallIntegerField(choices=[(1, 'worst'), (2, 'bad'), (3, 'just'), (4, 'good'), (5, 'best')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.Country'),
        ),
    ]
