# Generated by Django 3.0.3 on 2020-04-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reservation', models.BooleanField(default=False)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_no', to='api.Theater')),
            ],
        ),
    ]
