# Generated by Django 3.0.5 on 2020-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200412_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pro_num',
            field=models.ManyToManyField(related_name='myusers', through='api.Order', to='api.Product', verbose_name='구매한 상품'),
        ),
    ]
