# Generated by Django 3.0.5 on 2020-04-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200426_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='이름'),
        ),
    ]
