# Generated by Django 3.0.5 on 2020-04-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200414_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(blank=True, related_name='wished_bys', to='api.Movie'),
        ),
    ]
