# Generated by Django 3.0.3 on 2020-04-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200408_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_no', to='api.Theater'),
        ),
    ]
