# Generated by Django 3.0.3 on 2020-04-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_no', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Branch')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Screen')),
            ],
        ),
    ]
