# Generated by Django 3.0.3 on 2020-04-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200408_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
