# Generated by Django 3.0.3 on 2020-04-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reservationticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('price', models.IntegerField()),
                ('payment_option', models.CharField(max_length=20)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ReservationTicket')),
            ],
        ),
    ]
