# Generated by Django 3.0.3 on 2020-04-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200414_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationticket',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_ticktes', to='api.Schedule'),
        ),
        migrations.AlterField(
            model_name='reservationticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_tickets', to='api.Seat'),
        ),
        migrations.AlterField(
            model_name='reservationticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.Branch'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.Movie'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.Screen'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='api.Branch'),
        ),
    ]
