# Generated by Django 3.0.3 on 2020-04-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200417_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='running_time',
            field=models.TimeField(null=True),
        ),
    ]
