# Generated by Django 3.0.3 on 2020-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_schedule_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='running_time',
            field=models.DurationField(null=True),
        ),
    ]
