# Generated by Django 3.0.3 on 2020-04-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200423_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='finish_time',
            field=models.DateTimeField(),
        ),
    ]
