# Generated by Django 3.0.3 on 2020-04-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200423_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='running_time',
            field=models.TimeField(null=True),
        ),
    ]
