# Generated by Django 3.0.3 on 2020-04-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_schedule_running_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='running_time',
        ),
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.TimeField(null=True),
        ),
    ]
