# Generated by Django 3.0.3 on 2020-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200423_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='running_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='running_time',
            field=models.TimeField(null=True),
        ),
    ]
